### ISSUE TITLE
Item 3

### ISSUE THREAD

**Issue by guiimarques18** [pauloj2000/DSP-ES-2020-1-AvaLista#1]
Não apresentou os artefatos solicitados do Item 3 em diante.
Vocês tem 24h para apresentá-los e compor a nota, caso contrário será atribuída nota zero, devido ao prazo já ter-se findado.

**Comment by guiimarques18** [comment]
Vejam.

**Comment by augustobmoura** [comment]
Primeira versão foi commitada, estamos acompanhando as revisões nas issues #2 e #3
