### ISSUE TITLE
3.2.MER/mer-torneio.pdf

### ISSUE THREAD

**Issue by guiimarques18** [pauloj2000/DSP-ES-2020-1-AvaLista#2]
No MER é interessante que vocês estabeleçam as cardinalidade entre as relações. E os atributos de cada tabela.

Exemplo:
![image](https://user-images.githubusercontent.com/1537504/97450831-e611d980-1911-11eb-82c5-831206877acc.png)

**Comment by augustobmoura** [comment]
Vamos iniciar as correções

**Comment by Murilo001** [comment]
Resolvido.
