### ISSUE TITLE
3.3 UAP

### ISSUE THREAD

**Issue by guiimarques18** [pauloj2000/DSP-ES-2020-1-AvaLista#3]
Um modelo básico de caso de uso:
https://blog.hallanmedeiros.com/2010/03/29/documentacao-de-casos-de-uso/

Precisam melhorar as questões sobre formatação e organização dos documentos, um .txt é muito simplório.

**Comment by augustobmoura** [comment]
Vamos iniciar as correções

**Comment by Murilo001** [comment]
Resolvido.
